function applications(){
    var info = {
      "applicationTitles" : 
        [
                {"Laminating & Coating" : ["For over twenty five years, needlepunch fabrics made at the New England Nonwovens facility have been utilized as laminating and coating substrates. New England Nonwoven needlepunch fabrics are used in laminating process that include, wet adhesive bonding, dry web bonding, hot melt bonding, flame bonding and ultrasonic bonding. Needlepunch fabrics are also widely used in coating process such as, cast coating, expanded coating, extrusion coating, direct coating knife blade, direct coating gravure roll and direct screen coating. New England Nonwoven needlepunch fabrics are used to build composite structures where the needlepunch is used to provide bulk, body and resilience."]
            },
                {"Healthcare" : ["New England Nonwovens needlepunch 'soaker' fabric has been a mainstay in the manufacture of reusable incontinent pads and briefs over the years. These New England Nonwoven needlepunch fabrics are made to be highly absorbent and containing for liquids. Some needlepunch blends will wick very fast to move moisture away from the body and some will hold large volumes of fluids. Special fibers can be added to control the growth of odor causing bacteria and viruses. <br><br> New England Nonwoven needlepunch fabrics are used to make soft, comfortable surface fabrics for microwavable hot packs to ease muscle aches. Needlepunch felts are extensively used in orthordic braces and devices to provide a soft interface between the equipment and the body."]
            },
                {"Home Products" : ["Our needlepunch fabrics have many uses in 'home product'. Top of the bed items such as mattress pads, blankets and comforters are common uses for New England Nonwovens needlepunch fabrics. New England Nonwovens needlepunch fabrics are also widely use in pot holders, ironing boards, floor insulation, table pads, cushion pads, filters and in many more household items."]
            },
                {"Wipes" : ["Wipes of all kinds utilize New England Nonwovens needlepunch nonwoven fabrics. Some examples are: cosmetic wipes needing high absorbency and cleaning wipes that are fluid filled for ease of use and comfort. Wipes made from New England Nonwoven needlepunch fabrics that have high oil absorbency are used in environmental clean up operations."]
            },
                {"Mattresses &#45; Flame Retardant Barrier Fabrics": ["All mattresses made and sold in the United States after July 1st 2007 must meet the Federal Regulation 16 CFR part 1633 for flammability requirements. New England Nonwoven flame retardant needlepunch fabrics, made to the rigid standards provided by our customers, have been widely used to help mattress manufacturers meet this new Federal Standard. The flame retardant needlepunch fabrics can be quilted, laminated, combined, printed and sewn with other mattress components to provide effective fire barriers."]
            },
                {"Molding" : ["New England Nonwovens needlpunch fabrics can be made with blends of regular fibers and low melt fibers that allow the material to take and hold a shape in many molding applications. The needlepunch fabrics can also be saturated with polymer resins that allow the material to be molded with considerable rigidity. These molded needlepunch fabrics find there way into a variety of products such as automotive trunks and interiors, hats, medical products, filters, abrasive pads, insulators and many more."]
            },
                {"Automotive" : ["Needlepunch fabrics are extensively used in automotive applications in the trunk, under the hood and in the interior. The needlepunch fabrics can be made to provide heat insulation, acoustical barriers, filters for liquids and air and interior surface fabrics. <br><br> Soft needlepunch fabrics are used to make protective pads that mechanics place on the automobile to protect the paint and finish during repairs."]
            },
                {"Carpet Pads" : ["Needlepunch fabrics are commonly used to make carpet pads for carpets and rugs of all shapes and sizes. Polyester, polypropylene and wool are just some of the fibers used to make needlepunch fabric pads for the carpet and rug market. Needlepunch carpet pads have long been used to provide a layer of cushion, comfort and protection under carpets and rugs. New England Nonwovens needlepunch carpet pads from 10 to 30 ounces per yard are currently in use."]
            },
                {"Safety Mats" : ["New England Nonwovens polypropylene needlepunch cut into mats and placed around machinery can be an effective help in provided safe footing for operators. Polypropylene has an affinity for oil and thus can help keep floors subjected to machinery oils from becoming slippery. New England Nonwovens needlpunch fabrics have also been coated and laminated to provide fluid proof and high grip surfaces."]
            },
                {"Filtration" :["The use of needlepunch fabrics for filtering wet (liquids) and dry (particulates) media is extensive and encompasses a vast array of applications. New England Nonwovens needlepunch fabrics have been impregnated, calendered, singed, folded, laminated and combined with other materials for to make filters. Needlepunch fabrics can be made to absorb or repel various liquids, gases or particulates. Fibers and fiber blends can be chosen to make needlepunch fabrics that handle environmental extremes such as heat, cold, ultra violet light exposure, fluids and chemical concentrations. New England Nonwovens also has a stock program for Micron Rated Liquid Filtration. "]
            },
                {"Micron Rated Liquid Filtration Media &#45; Stock Program": ["New England Nonwovens stocks a broad line of micron rated liquid filter media. We stock several micron grades in polyester as well as polypropylene. In polyester we offer both singed and plain finish micron rated fabrics. New England Nonwovens stocks these items in 3, 5, 10, 25, 50, 75, 100, & 200 micron grades. The polypro is offered and stocked in 3 different widths, 21 &quot; , 23 &quot; and 72 &quot;. <br> <br> On the polypropylene side our standard finish is a glazed fabric. All of our polypropylene filter media are made from FDA compliant polypropylene staple fibers. We stock the polypro in 1, 3, 5, 10, 25, 50, 75, 100, & 200 micron grades. The polypro is offered and stocked in 3 widths 21&quot;, 23&quot;, and 72&quot;. <br><br> Our standard roll size for our 5 through 100 micron grades is 125 yards. On our 72&quot; products these are packaged individually. On our 20&quot;, 21&quot; and 23&quot; widths these items are packaged in rolls of 3. Our minimum order for the narrow widths would be 375 yards. apparel, sewn, decorative covers for pillows, appliances, furniture and wall decorations. Our standard rolls size for 1, 3, & 200 micron grades is 125 yards. As with the other microns the 72&quot; items are packaged individually and the narrow widths are in packages of 3. Our minimum order sizes are 100 and 300 yards respectively."]
            },
                {"Craft and Hobby": ["New England Nonwoven needlepunch fabrics have been made and used in many craft and hobby applications. Home products are a popular use including items such as linings for New England Nonwoven needlepunch fabric is used as base material for quilted items, needlepoint, hook rugs, over mitts and many others. Fibers and fiber blends of polyester, polypropylene, cotton and wool are popular in this market."]
            },
                {"Composites" : ["New England Nonwovens had the ability to &quotlayer&quot different fiber needlepunch webs as well as scrims, foams, woven fabrics and other nonwoven materials. The composite layers allow New England Nonwovens to build needlepunch fabrics that can have different properties and characteristics from one side versus the other. New England Nonwovens has built needlepunch composites for the mattress pad market with needlepunch and spunbonded layers. Layered needlpunch fabrics are used to draw moisture away from the top surface and absorb in the bottom layer for incontinent bed pads. The lamination industry uses New England Nonwovens needlepunch with urethane foam as substrate that has give and recovery when laminated or coated. Woven scrims are layered with New England Nonwovens needlepunch webs to give stability and strength."]
            }

        ]

    }
    ;

    var output = '<div class="container" id= "applicationList"> <h2>Applications</h2> <p><strong>Needlepunch Nonwoven Fabrics</strong> New England Nonwoven fabrics are use in a myriad of markets and applications. Click any of the drop downs below to learn more about some of the more prominent applications:</p> <div class="panel-group" id="accordion">';

    for (var i = 0; i <= info.applicationTitles.length; i++) {
        for (key in info.applicationTitles[i]) {
            if (info.applicationTitles[i].hasOwnProperty(key)) {
                output += '<div class="panel panel-default">' + '<div class="panel-heading">' + '<h4 class="panel-title">' + '<a data-toggle="collapse" data-parent="#accordion" href="#collapse' + i + '">' + key +'</a><span class="pull-right"><a data-toggle="collapse" data-parent="#accordion" href="#collapse' + i +'"><span class="toggle-icon glyphicon glyphicon-collapse-down"></span> </h4> </div> <div id="collapse' + i + '" class="panel-collapse collapse"><div class="panel-body">' + info.applicationTitles[i][key] + '</div> </div> </div>'
    ;
            } // hasOwnProperty check
        } // for each object
    } //for each array element

   $("#bodyHtml").html(output);
    }

function home(){
    
    var output = '<div class="jumbotron"><div class="container"><h1 class="display-3">New England Nonwoven</h1><hr class="m-y-2"><p>Needlepunch Nonwovens for: Laminating & Coating • Filtration • Health Care • Home Products • Molding</p><p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p></div></div><div class="container-fluid" id="bodyText"><div class="row" id="companySummary"><p>New England Nonwovens (formally the Deitsch Plastic non-woven division) is a leading manufacturer of engineered needlepunch nonwoven fabrics for a variety of markets and applications. Purchased in 2009 by long time industry executives Mike Hochlowski and John Uchmanowicz, New England Nonwovens has some of the most technically advanced machinery in North America. The company draws on an experienced work force, up to date equipment and broad based knowledge of its marketing, operations and technical support to create innovative solutions for customer applications. </p><p>New England Nonwovens draws on 30 years of manufacturing expertise and technical experience to provide innovative solutions for our customer&#39;s needlepunch fabric end uses. NEN has developed and produced needlepunch nonwoven fabrics for uses in health care, filtration, home crafts, bedding, CIPP pipe linings and composite building markets.</p><p>The strategic mission of NEN is to provide, innovative, superior quality needlepunch fabrics with excellent service and production flexibility to meet our customer&#39;s needs. New England Nonwovens works hand-in-hand with our customers to ensure the needlepunch fabric developed and produced meets the needs of the application. </p><p>Situated in a sizable manufacturing facility in West Haven CT with room to expand, New England Nonwovens anticipates steady growth over the next 5 years. NEN is looking forward to working with you to provide cost effective solutions to your needlepunch nonwoven requirements.</p></div>';
    $("#bodyHtml").html(output);
}